# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.flow_status_enum import FlowStatusEnum

class TestFlowStatusEnum(unittest.TestCase):
    """FlowStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFlowStatusEnum(self):
        """Test FlowStatusEnum"""
        # inst = FlowStatusEnum()

if __name__ == '__main__':
    unittest.main()
