# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.contact_already_exists import ContactAlreadyExists

class TestContactAlreadyExists(unittest.TestCase):
    """ContactAlreadyExists unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactAlreadyExists:
        """Test ContactAlreadyExists
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactAlreadyExists`
        """
        model = ContactAlreadyExists()
        if include_optional:
            return ContactAlreadyExists(
                error = '',
                contact = dripdrop.models.contact.Contact(
                    uuid = '', 
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    first_name = '', 
                    last_name = '', 
                    primary_email = null, 
                    primary_phone = null, 
                    custom_fields = {
                        'key' : null
                        }, 
                    tags = [
                        ''
                        ], )
            )
        else:
            return ContactAlreadyExists(
                error = '',
                contact = dripdrop.models.contact.Contact(
                    uuid = '', 
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    first_name = '', 
                    last_name = '', 
                    primary_email = null, 
                    primary_phone = null, 
                    custom_fields = {
                        'key' : null
                        }, 
                    tags = [
                        ''
                        ], ),
        )
        """

    def testContactAlreadyExists(self):
        """Test ContactAlreadyExists"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
