# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.outcome_enum import OutcomeEnum

class TestOutcomeEnum(unittest.TestCase):
    """OutcomeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutcomeEnum(self):
        """Test OutcomeEnum"""
        # inst = OutcomeEnum()

if __name__ == '__main__':
    unittest.main()
