# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.api.custom_fields_api import CustomFieldsApi


class TestCustomFieldsApi(unittest.TestCase):
    """CustomFieldsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomFieldsApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create a custom field definition
        """
        pass

    def test_destroy(self) -> None:
        """Test case for destroy

        Delete a custom field definition
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        List custom field definitions
        """
        pass

    def test_partial_update(self) -> None:
        """Test case for partial_update

        Patch a custom field definition
        """
        pass

    def test_retrieve(self) -> None:
        """Test case for retrieve

        Get a custom field definition
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update a custom field definition
        """
        pass


if __name__ == '__main__':
    unittest.main()
