# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.field_type_enum import FieldTypeEnum

class TestFieldTypeEnum(unittest.TestCase):
    """FieldTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldTypeEnum(self):
        """Test FieldTypeEnum"""
        # inst = FieldTypeEnum()

if __name__ == '__main__':
    unittest.main()
