# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.public_contact_duplicate_preview_response import PublicContactDuplicatePreviewResponse

class TestPublicContactDuplicatePreviewResponse(unittest.TestCase):
    """PublicContactDuplicatePreviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicContactDuplicatePreviewResponse:
        """Test PublicContactDuplicatePreviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicContactDuplicatePreviewResponse`
        """
        model = PublicContactDuplicatePreviewResponse()
        if include_optional:
            return PublicContactDuplicatePreviewResponse(
                resolutions = [
                    dripdrop.models.import_resolution.ImportResolution(
                        outcome = 'will_create', 
                        matched_by = '', 
                        matched_contact_uuid = '', 
                        is_ambiguous = True, 
                        notes = [
                            ''
                            ], )
                    ]
            )
        else:
            return PublicContactDuplicatePreviewResponse(
                resolutions = [
                    dripdrop.models.import_resolution.ImportResolution(
                        outcome = 'will_create', 
                        matched_by = '', 
                        matched_contact_uuid = '', 
                        is_ambiguous = True, 
                        notes = [
                            ''
                            ], )
                    ],
        )
        """

    def testPublicContactDuplicatePreviewResponse(self):
        """Test PublicContactDuplicatePreviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
