# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.custom_field_definition import CustomFieldDefinition

class TestCustomFieldDefinition(unittest.TestCase):
    """CustomFieldDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomFieldDefinition:
        """Test CustomFieldDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomFieldDefinition`
        """
        model = CustomFieldDefinition()
        if include_optional:
            return CustomFieldDefinition(
                uuid = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                display_name = '',
                key = '',
                field_type = 'char',
                target_model = '',
                target_model_display = '',
                required = True,
                description = '',
                options = None,
                sort_order = 0,
                is_archived = True,
                is_in_use = True
            )
        else:
            return CustomFieldDefinition(
                uuid = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                display_name = '',
                field_type = 'char',
                target_model = '',
                target_model_display = '',
                is_in_use = True,
        )
        """

    def testCustomFieldDefinition(self):
        """Test CustomFieldDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
