# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.current_password import CurrentPassword

class TestCurrentPassword(unittest.TestCase):
    """CurrentPassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrentPassword:
        """Test CurrentPassword
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurrentPassword`
        """
        model = CurrentPassword()
        if include_optional:
            return CurrentPassword(
                current_password = ''
            )
        else:
            return CurrentPassword(
                current_password = '',
        )
        """

    def testCurrentPassword(self):
        """Test CurrentPassword"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
