# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.public_flow_enrollment import PublicFlowEnrollment

class TestPublicFlowEnrollment(unittest.TestCase):
    """PublicFlowEnrollment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicFlowEnrollment:
        """Test PublicFlowEnrollment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicFlowEnrollment`
        """
        model = PublicFlowEnrollment()
        if include_optional:
            return PublicFlowEnrollment(
                uuid = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 0,
                flow_uuid = '',
                contact_uuid = ''
            )
        else:
            return PublicFlowEnrollment(
                uuid = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 0,
                flow_uuid = '',
                contact_uuid = '',
        )
        """

    def testPublicFlowEnrollment(self):
        """Test PublicFlowEnrollment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
