# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.api.flows_api import FlowsApi


class TestFlowsApi(unittest.TestCase):
    """FlowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlowsApi()

    def tearDown(self) -> None:
        pass

    def test_create_contact_and_enroll_create(self) -> None:
        """Test case for create_contact_and_enroll_create

        Create contact and enroll in flow
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        List flows
        """
        pass

    def test_retrieve(self) -> None:
        """Test case for retrieve

        Get a flow
        """
        pass


if __name__ == '__main__':
    unittest.main()
