# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.public_contact_bulk_create_response import PublicContactBulkCreateResponse

class TestPublicContactBulkCreateResponse(unittest.TestCase):
    """PublicContactBulkCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicContactBulkCreateResponse:
        """Test PublicContactBulkCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicContactBulkCreateResponse`
        """
        model = PublicContactBulkCreateResponse()
        if include_optional:
            return PublicContactBulkCreateResponse(
                created = [
                    dripdrop.models.contact.Contact(
                        uuid = '', 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        first_name = '', 
                        last_name = '', 
                        primary_email = null, 
                        primary_phone = null, 
                        custom_fields = {
                            'key' : null
                            }, 
                        tags = [
                            ''
                            ], )
                    ],
                skipped = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return PublicContactBulkCreateResponse(
                created = [
                    dripdrop.models.contact.Contact(
                        uuid = '', 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        first_name = '', 
                        last_name = '', 
                        primary_email = null, 
                        primary_phone = null, 
                        custom_fields = {
                            'key' : null
                            }, 
                        tags = [
                            ''
                            ], )
                    ],
        )
        """

    def testPublicContactBulkCreateResponse(self):
        """Test PublicContactBulkCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
