# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.paginated_duplicate_cluster_list import PaginatedDuplicateClusterList

class TestPaginatedDuplicateClusterList(unittest.TestCase):
    """PaginatedDuplicateClusterList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedDuplicateClusterList:
        """Test PaginatedDuplicateClusterList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedDuplicateClusterList`
        """
        model = PaginatedDuplicateClusterList()
        if include_optional:
            return PaginatedDuplicateClusterList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    dripdrop.models.duplicate_cluster.DuplicateCluster(
                        key_type = '', 
                        key_value = '', 
                        contacts = [
                            dripdrop.models.duplicate_cluster_contact.DuplicateClusterContact(
                                uuid = '', 
                                name = '', 
                                email = '', 
                                phone = '', )
                            ], )
                    ]
            )
        else:
            return PaginatedDuplicateClusterList(
                count = 123,
                results = [
                    dripdrop.models.duplicate_cluster.DuplicateCluster(
                        key_type = '', 
                        key_value = '', 
                        contacts = [
                            dripdrop.models.duplicate_cluster_contact.DuplicateClusterContact(
                                uuid = '', 
                                name = '', 
                                email = '', 
                                phone = '', )
                            ], )
                    ],
        )
        """

    def testPaginatedDuplicateClusterList(self):
        """Test PaginatedDuplicateClusterList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
