# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.create_contact_and_enroll import CreateContactAndEnroll

class TestCreateContactAndEnroll(unittest.TestCase):
    """CreateContactAndEnroll unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateContactAndEnroll:
        """Test CreateContactAndEnroll
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateContactAndEnroll`
        """
        model = CreateContactAndEnroll()
        if include_optional:
            return CreateContactAndEnroll(
                first_name = '',
                last_name = '',
                email = '',
                phone = '',
                custom_fields = {
                    'key' : null
                    }
            )
        else:
            return CreateContactAndEnroll(
                first_name = '',
        )
        """

    def testCreateContactAndEnroll(self):
        """Test CreateContactAndEnroll"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
