# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.models.on_match_enum import OnMatchEnum

class TestOnMatchEnum(unittest.TestCase):
    """OnMatchEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnMatchEnum(self):
        """Test OnMatchEnum"""
        # inst = OnMatchEnum()

if __name__ == '__main__':
    unittest.main()
