# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dripdrop.api.enrollments_api import EnrollmentsApi


class TestEnrollmentsApi(unittest.TestCase):
    """EnrollmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnrollmentsApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Enroll a contact
        """
        pass

    def test_destroy(self) -> None:
        """Test case for destroy

        Unenroll a contact
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        List enrollments
        """
        pass


if __name__ == '__main__':
    unittest.main()
