# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FieldTypeEnum(str, Enum):
    """
    * `char` - Text * `text` - Long Text * `integer` - Integer * `decimal` - Decimal * `boolean` - Boolean * `date` - Date * `datetime` - Date & Time * `email` - Email * `url` - URL * `choice` - Single Choice
    """

    """
    allowed enum values
    """
    CHAR = 'char'
    TEXT = 'text'
    INTEGER = 'integer'
    DECIMAL = 'decimal'
    BOOLEAN = 'boolean'
    DATE = 'date'
    DATETIME = 'datetime'
    EMAIL = 'email'
    URL = 'url'
    CHOICE = 'choice'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FieldTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


