# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FlowEnrollmentStatusesEnum(int, Enum):
    """
    * `0` - Not Started * `1` - Active * `2` - Paused * `3` - Error * `4` - Completed * `5` - Processing * `6` - Unsubscribed
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_4 = 4
    NUMBER_5 = 5
    NUMBER_6 = 6

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FlowEnrollmentStatusesEnum from a JSON string"""
        return cls(json.loads(json_str))


