# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FlowStatusEnum(int, Enum):
    """
    * `0` - Draft * `1` - Scheduled * `2` - Active * `3` - Paused * `4` - Complete * `5` - Archived
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_4 = 4
    NUMBER_5 = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FlowStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


