# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from dripdrop.models.outcome_enum import OutcomeEnum
from typing import Optional, Set
from typing_extensions import Self

class ImportResolution(BaseModel):
    """
    Per-row dedupe outcome in the import dry-run preview (aligned by row).
    """ # noqa: E501
    outcome: OutcomeEnum
    matched_by: Optional[StrictStr]
    matched_contact_uuid: Optional[UUID]
    is_ambiguous: StrictBool
    notes: List[StrictStr]
    __properties: ClassVar[List[str]] = ["outcome", "matched_by", "matched_contact_uuid", "is_ambiguous", "notes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImportResolution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if matched_by (nullable) is None
        # and model_fields_set contains the field
        if self.matched_by is None and "matched_by" in self.model_fields_set:
            _dict['matched_by'] = None

        # set to None if matched_contact_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.matched_contact_uuid is None and "matched_contact_uuid" in self.model_fields_set:
            _dict['matched_contact_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImportResolution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "outcome": obj.get("outcome"),
            "matched_by": obj.get("matched_by"),
            "matched_contact_uuid": obj.get("matched_contact_uuid"),
            "is_ambiguous": obj.get("is_ambiguous"),
            "notes": obj.get("notes")
        })
        return _obj


