# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OutcomeEnum(str, Enum):
    """
    * `will_create` - will_create * `will_update` - will_update * `will_skip` - will_skip
    """

    """
    allowed enum values
    """
    WILL_CREATE = 'will_create'
    WILL_UPDATE = 'will_update'
    WILL_SKIP = 'will_skip'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OutcomeEnum from a JSON string"""
        return cls(json.loads(json_str))


