# coding: utf-8

"""
    Drip Drop API

    API for integrations with Drip Drop.Authenticate by passing your API key in the `X-API-Key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from dripdrop.models.field_type_enum import FieldTypeEnum
from typing import Optional, Set
from typing_extensions import Self

class PatchedCustomFieldDefinition(BaseModel):
    """
    PatchedCustomFieldDefinition
    """ # noqa: E501
    uuid: Optional[UUID] = None
    created: Optional[datetime] = None
    modified: Optional[datetime] = None
    display_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Human-readable label for the custom field")
    key: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Machine-friendly identifier (e.g., 'company_name'). Auto-generated from display name if omitted.")
    field_type: Optional[FieldTypeEnum] = None
    target_model: Optional[StrictStr] = Field(default=None, description="Target model in 'app_label.model' format (e.g., 'contacts.contact')")
    target_model_display: Optional[StrictStr] = None
    required: Optional[StrictBool] = None
    description: Optional[StrictStr] = None
    options: Optional[Any] = Field(default=None, description="Configuration for the field (e.g., choices for 'choice' type, max_length for 'char')")
    sort_order: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    is_archived: Optional[StrictBool] = None
    is_in_use: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["uuid", "created", "modified", "display_name", "key", "field_type", "target_model", "target_model_display", "required", "description", "options", "sort_order", "is_archived", "is_in_use"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedCustomFieldDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "uuid",
            "created",
            "modified",
            "target_model_display",
            "is_in_use",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if options (nullable) is None
        # and model_fields_set contains the field
        if self.options is None and "options" in self.model_fields_set:
            _dict['options'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedCustomFieldDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "created": obj.get("created"),
            "modified": obj.get("modified"),
            "display_name": obj.get("display_name"),
            "key": obj.get("key"),
            "field_type": obj.get("field_type"),
            "target_model": obj.get("target_model"),
            "target_model_display": obj.get("target_model_display"),
            "required": obj.get("required"),
            "description": obj.get("description"),
            "options": obj.get("options"),
            "sort_order": obj.get("sort_order"),
            "is_archived": obj.get("is_archived"),
            "is_in_use": obj.get("is_in_use")
        })
        return _obj


