# coding: utf-8

"""
    Drip Drop API

    Documentation of API endpoints of Drip Drop

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from dripdrop.models.email_address import EmailAddress
from dripdrop.models.phone_number import PhoneNumber
from typing import Optional, Set
from typing_extensions import Self

class PatchedContact(BaseModel):
    """
    Serializer mixin that adds tag support to any model serializer.  The target model must have a ManyToManyField named `tags` pointing to tags.Tag.  Write request format: {\"tags\": [\"<tag-uuid>\", ...]} Read response format: {\"tags\": [{\"uuid\": \"...\", \"name\": \"...\", ...}, ...]}
    """ # noqa: E501
    uuid: Optional[UUID] = None
    created: Optional[datetime] = None
    modified: Optional[datetime] = None
    first_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    last_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    primary_email: Optional[EmailAddress] = None
    primary_phone: Optional[PhoneNumber] = None
    custom_fields: Optional[Dict[str, Any]] = None
    tags: Optional[List[UUID]] = None
    __properties: ClassVar[List[str]] = ["uuid", "created", "modified", "first_name", "last_name", "primary_email", "primary_phone", "custom_fields", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedContact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "uuid",
            "created",
            "modified",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of primary_email
        if self.primary_email:
            _dict['primary_email'] = self.primary_email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of primary_phone
        if self.primary_phone:
            _dict['primary_phone'] = self.primary_phone.to_dict()
        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['last_name'] = None

        # set to None if primary_email (nullable) is None
        # and model_fields_set contains the field
        if self.primary_email is None and "primary_email" in self.model_fields_set:
            _dict['primary_email'] = None

        # set to None if primary_phone (nullable) is None
        # and model_fields_set contains the field
        if self.primary_phone is None and "primary_phone" in self.model_fields_set:
            _dict['primary_phone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedContact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "created": obj.get("created"),
            "modified": obj.get("modified"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "primary_email": EmailAddress.from_dict(obj["primary_email"]) if obj.get("primary_email") is not None else None,
            "primary_phone": PhoneNumber.from_dict(obj["primary_phone"]) if obj.get("primary_phone") is not None else None,
            "custom_fields": obj.get("custom_fields"),
            "tags": obj.get("tags")
        })
        return _obj


